// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otjazfkzuxfmbnbnrpwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90amF6Zmt6dXhmbWJuYm5ycHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzE5MTQsImV4cCI6MjA2NTMwNzkxNH0.ntPZ2uMuF2FKZ_eD3ezwrqd19epjlBXGx-tGJrzKp_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);